import Head from "next/head";
import styles from "../styles/Layout.module.css";
import Header from "./Header";
import Navbar from "./Navbar";

const Layout = (props) => {
	return (
		<div>
			<Head>
				<title>Pilkom News</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<Navbar />
			<div className={styles.container}>
				<Header />
				<main className={styles.main}>{props.children}</main>
			</div>
		</div>
	);
};

export default Layout;
